name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'gauchograduate/package-lock.json'

    - name: Install Dependencies
      working-directory: ./gauchograduate
      run: npm ci --legacy-peer-deps

    - name: Run Tests
      working-directory: ./gauchograduate
      run: npm test
      env:
        POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
